version: "3.7"

networks:
  lhnet:
    driver: bridge

services:
  elasticsearch:
    image: 'bitnami/elasticsearch:latest'
    networks:
      - lhnet
    ports:
      - "9200:9200"

  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - lhnet
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://kafka:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

  lhconsumer:
    image: 'lhconsumer:latest'
    networks:
      - lhnet
    environment:
      ELASTICSEARCH_ADDRESSES: "http://elasticsearch:9200"
      ELASTICSEARCH_INDEX: "kra_logs"
      KAFKA_BROKERS: "kafka:9094"
      KAFKA_TOPIC: "cvl-kra-logs"
    depends_on:
      - kafka

  kibana:
    image: 'bitnami/kibana:latest'
    networks:
      - lhnet
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"

  pg:
    image: bitnami/postgresql
    container_name: alya-pg
    networks:
      - lhnet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5434"

  redis:
    image: redis
    container_name: alya-redis
    networks:
      - lhnet
    ports:
      - "6378:6378"

  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - lhnet
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

volumes:
  minio-data:
